variable "turso_url" {
  type    = string
  default = getenv("TURSO_DATABASE_URL")
}

variable "turso_token" {
  type    = string
  default = getenv("TURSO_AUTH_TOKEN")
}

env "turso" {
  url = "${var.turso_url}?authToken=${var.turso_token}"
  
  # Source of truth for schema (generated by Drizzle)
  src = "file://schema.sql"

  migration {
    dir = "file://migrations"
  }

  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }

  # LibSQL/Turso specific dev database
  dev = "sqlite://dev?mode=memory"
}
